/* DSblock model generated by Dymola from Modelica model TEST.test1
 Dymola Version 2015 FD01 (64-bit), 2014-11-04 translated this at Mon Feb 29 16:05:46 2016

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="TEST.test1";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/ottelien/appdata/roaming/dynasim/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[0] = 0;
W_[6] = 0.0;
W_[2] = 0.0;
W_[4] = 0.0;
BoundParameterSection
 /* Linear system of equations to solve. */
W_[1] = 0.0;
SolveScalarLinearParametric( -DP_[0]," -thermalConductor.G", 0.0,"0.0", W_[1],
  "thermalConductor.dT");
 /* End of Equation Block */ 

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
W_[3] = 288.15;
F_[0] = 0;
#endif
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection
W_[5] = DP_[2]*(1+DP_[4]*(X_[0]-DP_[3]));
 /* Linear system of equations to solve. */
F_[0] = RememberSimple_(F_[0], 0);
SolveScalarLinearParametric(DP_[1],"heatCapacitor.C", W_[5],"heatCapacitor.port.Q_flow",
   F_[0],"der(heatCapacitor.T)");
 /* End of Equation Block */ 


AcceptedSection1

AcceptedSection2
W_[3] = X_[0]-W_[1];

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("thermalConductor.Q_flow", "Heat flow rate from port_a -> port_b [W]",\
 0, 0.0,0.0,0.0,0,513)
DeclareVariable("thermalConductor.dT", "port_a.T - port_b.T [K,]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareAlias2("thermalConductor.port_a.T", "Port temperature [K|degC]", \
"heatCapacitor.T", 1, 1, 0, 4)
DeclareVariable("thermalConductor.port_a.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,777)
DeclareVariable("thermalConductor.port_b.T", "Port temperature [K|degC]", 288.15,\
 0.0,1E+100,300.0,0,520)
DeclareVariable("thermalConductor.port_b.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,777)
DeclareParameter("thermalConductor.G", "Constant thermal conductance of material [W/K]",\
 0, 0.005, 0.0,0.0,0.0,0,560)
DeclareParameter("heatCapacitor.C", "Heat capacity of element (= cp*m) [J/K]", 1,\
 5, 0.0,0.0,0.0,0,560)
DeclareState("heatCapacitor.T", "Temperature of element [K|degC]", 0, 293.15, \
0.0,1E+100,300.0,0,560)
DeclareDerivative("heatCapacitor.der(T)", "der(Temperature of element) [K/s]", 0,\
 0.0,0.0,0.0,0,512)
DeclareAlias2("heatCapacitor.der_T", "Time derivative of temperature (= der(T)) [K/s]",\
 "heatCapacitor.der(T)", 1, 6, 0, 0)
DeclareAlias2("heatCapacitor.port.T", "Port temperature [K|degC]", \
"heatCapacitor.T", 1, 1, 0, 4)
DeclareVariable("heatCapacitor.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareParameter("fixedHeatFlow.Q_flow", "Fixed heat flow rate at port [W]", 2, 1000,\
 0.0,0.0,0.0,0,560)
DeclareParameter("fixedHeatFlow.T_ref", "Reference temperature [K|degC]", 3, \
293.15, 0.0,1E+100,300.0,0,560)
DeclareParameter("fixedHeatFlow.alpha", "Temperature coefficient of heat flow rate [1/K]",\
 4, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("fixedHeatFlow.port.T", "Port temperature [K|degC]", \
"heatCapacitor.T", 1, 1, 0, 4)
DeclareAlias2("fixedHeatFlow.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "heatCapacitor.port.Q_flow", -1, 5, 5, 132)
DeclareAlias2("temperatureSensor.T", "Absolute temperature as output signal [K]",\
 "thermalConductor.port_b.T", 1, 5, 3, 0)
DeclareAlias2("temperatureSensor.port.T", "Port temperature [K|degC]", \
"thermalConductor.port_b.T", 1, 5, 3, 4)
DeclareVariable("temperatureSensor.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,777)
EndNonAlias(0)
#define NX_    1
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    7
#define NP_    5
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1245095064
#define NHash2_ 752519693
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    7
#define SizePre_ 0
#define SizeEq_ 1
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(F_[0], 0, 0);
EndEqBlock
EndDataBlock
